openapi: 3.0.3
info:
  title: Esyfo Narmesteleder API
  version: 1.0.2
  description: |
    API v1 for linemanager creation, revoke, requirement, and metrics.
    
    This api require authentication with Maskinporten or Idporten Level 4 issued JWT.
    
    The Maskinporten token must be issued to a SystemUser with
    scope `nav:syfo/narmesteleder/lps` and Altinn resource `nav_syfo_oppgi-narmesteleder`.
    
    DEV: In Swagger UI, select the server in the “Servers” dropdown that matches the URL where Swagger UI is hosted. If the selected server uses a different host\/origin, the browser will treat requests as cross\-origin and you may get CORS preflight errors.

servers:
  - url: https://narmesteleder-api.ekstern.dev.nav.no
    description: Test server for assigning line manager to employees on sick leave.
  - url: https://esyfo-narmesteleder.ekstern.dev.nav.no
    description: Legacy test server for assigning line manager to employees on sick leave(will be removed soon).
  - url: https://narmesteleder-api.nav.no
    description: Production server for assigning line manager to employees on sick leave.
paths:
  /api/v1/linemanager:
    post:
      summary: Assign linemanager to employee on sick leave
      description: Assigns a linemanager to an employee on sick leave. Will override any existing linemanger.
      tags: [ linemanager ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Linemanager'
      responses:
        '202':
          description: Request accepted for processing
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/linemanager/revoke:
    post:
      summary: Revoke existing linemanager for employee on sick leave
      description: Publishes a revoke event to Kafka.
      tags: [ linemanager ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinemanagerRevoke'
      responses:
        '202':
          description: Revocation accepted
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/linemanager/requirement:
    get:
      summary: Get collection of linemanager requirement
      description: Returns response with a list containing items with details about outstandig requirements for linemanager for employees.
      tags: [ requirement ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      parameters:
        - name: createdAfter
          in: query
          required: true
          example: 2025-12-04T09:04:44.261429Z
          description: Filter results created after this timestamp (ISO 8601)
          schema:
            type: string
            format: date-time
        - name: orgNumber
          in: query
          required: true
          description: Organization number (digits only)
          schema:
            type: string
            pattern: '^\d+$'
        - name: pageSize
          in: query
          required: false
          description: Number of results per page. If a value higher than 50 is provided, it will be capped to 50.
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 50
      responses:
        '200':
          description: Requirement details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinemanagerRequirementCollection'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Requirement not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/linemanager/requirement/{id}:
    put:
      summary: Assigns a linemanager for employee with requirement
      description: Assigns a linemanager to the employee with requirement idenified by the id parameter
      tags: [ requirement ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: Requirement UUID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Manager'
      responses:
        '202':
          description: Update accepted
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Requirement not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    get:
      summary: Get linemanager requirement
      description: Returns details about the requirement for linemanager for an employee.
      tags: [ requirement ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: Requirement UUID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Requirement details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinemanagerRequirementRead'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Requirement not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  securitySchemes:
    maskinporten_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Systemuser token from Maskinporten. Using scope nav:syfo/narmesteleder/lps and resource nav_syfo_oppgi-narmesteleder
    tokenx_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: TokenX issued JWT.
  schemas:
    Linemanager:
      type: object
      properties:
        employeeIdentificationNumber:
          type: string
          description: "A Norwegian national identity number or D number."
          example: "12345678901"
        lastName:
          type: string
          description: The last name of the employee. Used to validate against the registered value in folkeregisteret. Validation is case-insensitive.
          example: "Hansen"
        orgNumber:
          type: string
          description: Organization number where the employee works
          example: "123456789"
        manager:
          $ref: '#/components/schemas/Manager'
      required:
        - employeeIdentificationNumber
        - lastName
        - orgNumber
        - manager

      description: Linemanager relation payload.
      additionalProperties: true
    LinemanagerRevoke:
      type: object
      properties:
        employeeIdentificationNumber:
          type: string
          description: "A Norwegian national identity number or D number."
          example: "12345678901"
        orgNumber:
          type: string
          description: Organization number where the employee works
          example: "123456789"
        lastName:
          type: string
          description: The last name of the employee.
          example: "Hansen"
      required:
        - employeeIdentificationNumber
        - orgNumber
        - lastName
      description: Linemanager revoke payload.
      additionalProperties: true
    Manager:
      type: object
      description: Manager details payload.
      properties:
        nationalIdentificationNumber:
          type: string
          description: Norwegian national identity number or D number of the manager.
          example: "10987654321"
        lastName:
          type: string
          description: The last name of the manager. Used to validate against the registered value in folkeregisteret. Validation is case-insensitive.
          example: "Jensen"
        mobile:
          type: string
          description: Mobile phone number of the manager.
          example: "+4790000000"
        email:
          type: string
          format: email
          description: Email address of the manager.
          example: "leder@example.com"
      required:
        - nationalIdentificationNumber
        - lastName
        - mobile
        - email
      additionalProperties: false
    LinemanagerRequirementRead:
      type: object
      description: Details related to the requirement an employee has for linemanager.
      properties:
        id:
          type: string
          format: uuid
          description: Requirement UUID.
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        employeeIdentificationNumber:
          type: string
          description: Norwegian national identity number or D number of the employee.
          example: "12345678901"
        orgNumber:
          type: string
          description: Organization number where the employee works.
          example: "123456789"
        orgName:
          type: string
          nullable: true
          description: Organization name (if available).
          example: "Eksempel AS"
        mainOrgnumber:
          type: string
          description: Main (parent) organization number.
          example: "987654321"
        managerIdentificationNumber:
          type: string
          nullable: true
          description: Norwegian national identity number or D number of the manager, for the previous linemanager the employee had, if any.
          example: "10987654321"
        name:
          type: object
          description: Name of the employee on sick leave.
          properties:
            firstName:
              type: string
              description: First name.
              example: "Ola"
            middleName:
              type: string
              description: Middle name.
              example: "Ola"
            lastName:
              type: string
              description: Last name.
              example: "Nordmann"
          required:
            - firstName
            - lastName
          additionalProperties: false
        created:
          type: string
          format: date-time
          description: Timestamp when the requirement was created
        updated:
          type: string
          format: date-time
          description: Timestamp when the requirement was last updated
        status:
          type: string
          description: |
            Status types for requirements.
            * `CREATED`: A requirement to get a linemanager assigned has been identified. The requirement is stored in our database but we have not yet sent it to Dialogporten.
            * `REQUIRES_ATTENTION`: A requirement to get a linemanager assigned has created in our database AND it has been delivered to Dialogporten.
            * `COMPLETED`: There is no longer a need to assign linemanger for this requirement. Probably because a linemanager has been assigned.
            * `ERROR`: An unexpected error occurred in the process of handling the requirement. No need for api consumers to take action.
          enum:
            - CREATED
            - REQUIRES_ATTENTION
            - COMPLETED
            - ERROR
        revokedBy:
          type: string
          nullable: true
          description: If a previous linemanager was revoked, this field reveals if employee, linemanager or lps triggered the revoke.
          enum:
            - LINEMANAGER
            - EMPLOYEE
            - LPS
      required:
        - id
        - employeeIdentificationNumber
        - orgNumber
        - mainOrgnumber
        - name
        - created
        - updated
        - status
      additionalProperties: false
    LinemanagerRequirementCollection:
      type: object
      properties:
        linemanagerRequirements:
          type: array
          items:
            $ref: '#/components/schemas/LinemanagerRequirementRead'
        meta:
          $ref: '#/components/schemas/PageInfo'
      required:
        - linemanagerRequirements
        - meta

    PageInfo:
      description: Information about the pageSize and number of items in the result set.
      type: object
      properties:
        size:
          type: integer
        pageSize:
          type: integer
        hasMore:
          description: Indicates if there are more results available beyond the current page.
          type: boolean
      required:
        - size
        - pageSize
        - hasMore
    ErrorType:
      type: string
      description: |
        Application error type.
        * `AUTHENTICATION_ERROR`: Authentication failed due to missing or invalid credentials.
        * `AUTHORIZATION_ERROR`: Authorization failed due to insufficient permissions.
        * `NOT_FOUND`: The requested resource was not found.
        * `INTERNAL_SERVER_ERROR`: An unexpected error occurred on the server.
        * `ILLEGAL_ARGUMENT`: The request contained an illegal argument.
        * `BAD_REQUEST`: The request was malformed or contained invalid data.
        * `INVALID_FORMAT`: The request contained json data in invalid format and could not be deserialized.
        * `CONFLICT`: The request could not be completed due to a conflict with the current state of the resource.
        * `LINEMANAGER_MISSING_EMPLOYMENT_IN_ORG`: The linemanager does not have an active employment in any sub organization under the parent of the specified organization.
        * `EMPLOYEE_MISSING_EMPLOYMENT_IN_ORG`: The employee does not have an active employment in the specified organization.
        * `LINEMANAGER_NAME_NATIONAL_IDENTIFICATION_NUMBER_MISMATCH`: The name provided for the linemanager does not match the name registered with the provided national identification number.
        * `EMPLOYEE_NAME_NATIONAL_IDENTIFICATION_NUMBER_MISMATCH`: The name provided for the employee does not match the name registered with the provided national identification number.
        * `MISSING_ORG_ACCESS`: The entity making the request does not have access to the specified organization.
        * `MISSING_ALITINN_RESOURCE_ACCESS`: The entity making the request does not have access to the required Altinn resource.
        * `NO_ACTIVE_SICK_LEAVE`: The employee does not have an active sick leave.
        * `MISSING_REQUIRED_PARAMETER`: A required parameter is missing from the request.
      enum:
        - AUTHENTICATION_ERROR
        - AUTHORIZATION_ERROR
        - NOT_FOUND
        - INTERNAL_SERVER_ERROR
        - ILLEGAL_ARGUMENT
        - BAD_REQUEST
        - INVALID_FORMAT
        - CONFLICT
        - LINEMANAGER_MISSING_EMPLOYMENT_IN_ORG
        - EMPLOYEE_MISSING_EMPLOYMENT_IN_ORG
        - LINEMANAGER_NAME_NATIONAL_IDENTIFICATION_NUMBER_MISMATCH
        - EMPLOYEE_NAME_NATIONAL_IDENTIFICATION_NUMBER_MISMATCH
        - MISSING_ORG_ACCESS
        - MISSING_ALITINN_RESOURCE_ACCESS
        - NO_ACTIVE_SICK_LEAVE
        - MISSING_REQUIRED_PARAMETER
    ApiError:
      type: object
      description: Standard error payload.
      properties:
        status:
          type: object
          properties:
            value:
              type: integer
              format: int32
              description: HTTP status code that matches the status of the request.
              example: 400
            description:
              type: string
              description: Status description appropriate for the status value.
              example: Bad Request
        type:
          $ref: '#/components/schemas/ErrorType'
        message:
          type: string
          description: Human readable error message.
          example: Validation failed for field orgNumber
        path:
          type: string
          nullable: true
          description: Request path.
          example: /api/v1/linemanager
        timestamp:
          type: string
          format: date-time
          description: Error creation time (UTC).
          example: 2024-05-01T12:34:56Z
      required:
        - status
        - type
        - message
        - timestamp
      additionalProperties: false
tags:
  - name: linemanager
    description: Linemanager relation operations.
  - name: requirement
    description: Linemanager requirement operations.
  - name: metrics
    description: Operational metrics.
