openapi: 3.0.3
info:
  title: Esyfo Narmesteleder API
  version: 1.0.0
  description: |
    API v1 for linemanager creation, revoke, requirement, and metrics.
    
    This api require authentication with Maskinporten or Idporten Level 4 issued JWT.
    
    The Maskinporten token must be issued to a SystemUser with
    scope `nav:syfo/narmesteleder/lps` and Altinn resource `nav_syfo_oppgi-narmesteleder`.
servers:
  - url: https://esyfo-narmesteleder.ekstern.dev.nav.no
    description: Test server for assigning line manager to employees on sick leave.
paths:
  /api/v1/linemanager:
    post:
      summary: Assign linemanager to employee on sick leave
      description: Assigns a linemanager to an employee on sick leave. Will override any existing linemanger.
      tags: [ linemanager ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Linemanager'
      responses:
        '202':
          description: Request accepted for processing
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/linemanager/revoke:
    post:
      summary: Revoke existing linemanager for employee on sick leave
      description: Publishes a revoke event to Kafka.
      tags: [ linemanager ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinemanagerRevoke'
      responses:
        '202':
          description: Revocation accepted
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/linemanager/requirement/{id}:
    put:
      summary: Assigns a linemanager for employee with requirement
      description: Assigns a linemanager to the employee with requirement idenified by the id parameter
      tags: [ requirement ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: Requirement UUID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Manager'
      responses:
        '202':
          description: Update accepted
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Requirement not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    get:
      summary: Get linemanager requirement
      description: Returns details about the requirement for linemanager for an employee.
      tags: [ requirement ]
      security:
        - maskinporten_jwt: [ ]
        - tokenx_jwt: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: Requirement UUID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Requirement details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinemanagerRequirementRead'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Requirement not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  securitySchemes:
    maskinporten_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Systemuser token from Maskinporten. Using scope nav:syfo/narmesteleder/lps and resource nav_syfo_oppgi-narmesteleder
    tokenx_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: TokenX issued JWT.
  schemas:
    Linemanager:
      type: object
      properties:
        employeeIdentificationNumber:
          type: string
          description: "A Norwegian national identity number or D number."
          example: "12345678901"
        orgNumber:
          type: string
          description: Organisation number where the employee works
          example: "123456789"
        manager:
          $ref: '#/components/schemas/Manager'

      description: Linemanager relation payload.
      additionalProperties: true
    LinemanagerRevoke:
      type: object
      properties:
        employeeIdentificationNumber:
          type: string
          description: "A Norwegian national identity number or D number."
          example: "12345678901"
        orgNumber:
          type: string
          description: Organisation number where the employee works
          example: "123456789"
      description: Linemanager revoke payload.
      additionalProperties: true
    Manager:
      type: object
      description: Manager details payload.
      properties:
        nationalIdentificationNumber:
          type: string
          description: Norwegian national identity number or D number of the manager.
          example: "10987654321"
        mobile:
          type: string
          description: Mobile phone number of the manager.
          example: "+4790000000"
        email:
          type: string
          format: email
          description: Email address of the manager.
          example: "leder@example.com"
      required:
        - nationalIdentificationNumber
        - mobile
        - email
      additionalProperties: false
    LinemanagerRequirementRead:
      type: object
      description: Details related to the requirement an employee has for linemanager.
      properties:
        id:
          type: string
          format: uuid
          description: Requirement UUID.
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        employeeIdentificationNumber:
          type: string
          description: Norwegian national identity number or D number of the employee.
          example: "12345678901"
        orgNumber:
          type: string
          description: Organisation number where the employee works.
          example: "123456789"
        orgName:
          type: string
          nullable: true
          description: Organisation name (if available).
          example: "Eksempel AS"
        mainOrgnumber:
          type: string
          description: Main (parent) organisation number.
          example: "987654321"
        managerIdentificationNumber:
          type: string
          nullable: true
          description: Norwegian national identity number or D number of the manager, for the previous linemanager the employee had, if any.
          example: "10987654321"
        name:
          type: object
          description: Name of the employee on sick leave.
          properties:
            firstName:
              type: string
              description: First name.
              example: "Ola"
            middleName:
              type: string
              description: Middle name.
              example: "Ola"
            lastName:
              type: string
              description: Fast name.
              example: "Nordmann"
          required:
            - firstName
            - lastName
          additionalProperties: false
        created:
          type: string
          format: date-time
          description: Timestamp when the requirement was created
        updated:
          type: string
          format: date-time
          description: Timestamp when the requirement was last updated
        status:
          type: string
          description: Status of the requirement
          enum:
            - BEHOV_CREATED
            - DIALOGPORTEN_STATUS_SET_REQUIRES_ATTENTION
            - BEHOV_FULFILLED
            - DIALOGPORTEN_STATUS_SET_COMPLETED
            - ERROR
        revokedBy:
          type: string
          nullable: true
          description: If a previous linemanager was revoked, this field reveals if employee, linemanager or lps triggered the revoke.
          enum:
            - LINEMANAGER
            - EMPLOYEE
            - LPS
      required:
        - id
        - employeeIdentificationNumber
        - orgNumber
        - mainOrgnumber
        - name
        - created
        - updated
        - status
      additionalProperties: false
    ErrorType:
      type: string
      description: Application error type.
      enum:
        - AUTHENTICATION_ERROR
        - AUTHORIZATION_ERROR
        - NOT_FOUND
        - INTERNAL_SERVER_ERROR
        - ILLEGAL_ARGUMENT
        - BAD_REQUEST
        - CONFLICT
    ApiError:
      type: object
      description: Standard error payload.
      properties:
        status:
          type: integer
          format: int32
          description: HTTP status code.
          example: 400
        type:
          $ref: '#/components/schemas/ErrorType'
        message:
          type: string
          description: Human readable error message.
          example: Validation failed for field orgNumber
        path:
          type: string
          nullable: true
          description: Request path.
          example: /api/v1/linemanager
        timestamp:
          type: string
          format: date-time
          description: Error creation time (UTC).
          example: 2024-05-01T12:34:56Z
      required:
        - status
        - type
        - message
        - timestamp
      additionalProperties: false
tags:
  - name: linemanager
    description: Linemanager relation operations.
  - name: requirement
    description: Linemanager requirement operations.
  - name: metrics
    description: Operational metrics.
