openapi: 3.0.3
info:
  title: Esyfo Oppfolgingsansvarlig API
  version: 1.0.0
  description: API v1 for linemanager creation, revoke, requirement, and metrics.
servers:
  - url: https://esyfo-narmesteleder.ekstern.dev.nav.no
paths:
  /api/v1/linemanager:
    post:
      summary: Create or update linemanager relation
      description: Publishes a linemanager relation to Kafka.
      tags: [linemanager]
      security:
        - maskinporten_jwt: []
        - tokenx_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Linemanager'
      responses:
        '202':
          description: Request accepted for processing
        '400':
          description: Validation failed
        '401':
          description: Unauthorized
  /api/v1/linemanager/revoke:
    post:
      summary: Revoke linemanager relation
      description: Publishes a revoke event to Kafka.
      tags: [linemanager]
      security:
        - maskinporten_jwt: []
        - tokenx_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinemanagerRevoke'
      responses:
        '202':
          description: Revocation accepted
        '400':
          description: Validation failed
        '401':
          description: Unauthorized
  /api/v1/linemanager/requirement/{id}:
    put:
      summary: Update linemanager requirement
      description: Updates requirement by UUID.
      tags: [requirement]
      security:
        - maskinporten_jwt: []
        - tokenx_jwt: []
      parameters:
        - name: id
          in: path
          required: true
          description: Requirement UUID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Manager'
      responses:
        '202':
          description: Update accepted
        '400':
          description: Validation failed
        '401':
          description: Unauthorized
        '404':
          description: Requirement not found
    get:
      summary: Get linemanager requirement
      description: Returns requirement details by UUID.
      tags: [requirement]
      security:
        - maskinporten_jwt: []
        - tokenx_jwt: []
      parameters:
        - name: id
          in: path
          required: true
          description: Requirement UUID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Requirement details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinemanagerRequirement'
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /internal/metrics:
    get:
      summary: Scrape application metrics
      description: Returns Prometheus metrics.
      tags: [metrics]
      responses:
        '200':
          description: Prometheus exposition format
          content:
            text/plain:
              schema:
                type: string
components:
  securitySchemes:
    maskinporten_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Maskinporten issued JWT.
    tokenx_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: TokenX issued JWT.
  schemas:
    Linemanager:
      type: object
      description: Linemanager relation payload.
      additionalProperties: true
    LinemanagerRevoke:
      type: object
      description: Linemanager revoke payload.
      additionalProperties: true
    Manager:
      type: object
      description: Updated requirement payload.
      additionalProperties: true
    LinemanagerRequirement:
      type: object
      description: Requirement details payload.
      additionalProperties: true
tags:
  - name: linemanager
    description: Linemanager relation operations.
  - name: requirement
    description: Linemanager requirement operations.
  - name: metrics
    description: Operational metrics.
