apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: esyfo-narmesteleder
  namespace: team-esyfo
spec:
  ingresses:
    - https://esyfo-narmesteleder.intern.dev.nav.no
  image: {{image}} #
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  replicas:
    max: 2
    min: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
