apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: esyfo-narmesteleder
  namespace: team-esyfo
  annotations:
    texas.nais.io/enabled: "true"
spec:
  ingresses:
    - https://esyfo-narmesteleder.intern.dev.nav.no
    - https://esyfo-narmesteleder.ekstern.dev.nav.no/api/v1/linemanager
  image: {{image}} #
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  replicas:
    max: 2
    min: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        name: esyfo-narmesteleder-instance
        collation: nb_NO.UTF8
        databases:
          - name: esyfo-narmesteleder-db
            envVarPrefix: NARMESTELEDER_DB
        diskAutoresize: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          delegationSource: altinn
          enabled: true
          product: syfo
          separator: "/"
          name: narmesteleder/lps
          atMaxAge: 680
      consumes:
        - name: "digdir:dialogporten.serviceprovider"
        - name: "altinn:authorization/authorize"
  azure:
    application:
      enabled: true
  leaderElection: true
  accessPolicy:
    inbound:
      rules:
        - application: tokenx-token-generator
          namespace: nais
        - application: narmesteleder-frontend
    outbound:
      rules:
        - application: dinesykmeldte-backend
        - application: arbeidsgiver-altinn-tilganger
          namespace: fager
      external:
        - host: aareg-services-q2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: "platform.tt02.altinn.no"
  kafka:
    pool: nav-dev
  env:
    - name: PDL_BASE_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: dev-fss.pdl.pdl-api
    - name: AAREG_BASE_URL
      value: https://aareg-services-q2.dev-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: dev-fss.arbeidsforhold.aareg-services-nais
    - name: DIALOGPORTEN_SCOPE
      value: "digdir:dialogporten.serviceprovider"
    - name: ALTINN_3_BASE_URL
      value: "https://platform.tt02.altinn.no"
    - name: DINESYMELDTE_BASEURL
      value: http://dinesykmeldte-backend
    - name: DINESYMELDTE_SCOPE
      value: dev-gcp.team-esyfo.dinesykmeldte-backend
    - name: ALTINN_TILGANGER_BASE_URL
      value: http://arbeidsgiver-altinn-tilganger.fager
    - name: FRONTEND_BASE_URL
      value: https://www.ekstern.dev.nav.no/arbeidsgiver
    - name: PUBLIC_INGRESS_URL
      value: https://esyfo-narmesteleder.ekstern.dev.nav.no
    - name: PERSIST_LEESAH_NL_BEHOV
      value: "true"
  envFrom:
    - secret: altinn-subscription-key
