alter type BEHOV_STATUS RENAME VALUE 'RECEIVED' TO 'BEHOV_CREATED';
alter type BEHOV_STATUS RENAME VALUE 'PENDING' TO 'DIALOGPORTEN_STATUS_SET_REQUIRES_ATTENTION';
alter type BEHOV_STATUS RENAME VALUE 'COMPLETED' TO 'BEHOV_FULFILLED';
alter type BEHOV_STATUS ADD VALUE 'DIALOGPORTEN_STATUS_SET_COMPLETED';
